// =============================================
// 🔭 TELESCOPE WEB - DATA LAYER
// All data from CSV files and Python source
// =============================================

const STARS = [
  { name: "Sun", magnitude: 4.8, temperature: 5840, type: "G", distance: 0.0, radius: 1.0, ra: null, dec: null, constellation: "Solar System" },
  { name: "Sirius A", magnitude: 1.4, temperature: 9620, type: "A", distance: 8.6, radius: 1.71, ra: 101.287, dec: -16.716, constellation: "Canis Major" },
  { name: "Canopus", magnitude: -3.1, temperature: 7400, type: "F", distance: 310, radius: 77, ra: 95.988, dec: -52.696, constellation: "Carina" },
  { name: "Arcturus", magnitude: -0.4, temperature: 4590, type: "K", distance: 36.7, radius: 25, ra: 213.915, dec: 19.182, constellation: "Boötes" },
  { name: "Alpha Centauri A", magnitude: 4.3, temperature: 5840, type: "G", distance: 4.37, radius: 1.2, ra: 219.902, dec: -60.834, constellation: "Centaurus" },
  { name: "Vega", magnitude: 0.5, temperature: 9900, type: "A", distance: 25, radius: 2.4, ra: 279.235, dec: 38.784, constellation: "Lyra" },
  { name: "Capella", magnitude: -0.6, temperature: 5150, type: "G", distance: 42.9, radius: 12, ra: 79.172, dec: 45.998, constellation: "Auriga" },
  { name: "Rigel", magnitude: -7.2, temperature: 12140, type: "B", distance: 860, radius: 78, ra: 78.634, dec: -8.202, constellation: "Orion" },
  { name: "Procyon A", magnitude: 2.6, temperature: 6600, type: "F", distance: 11.4, radius: 2.04, ra: 114.825, dec: 5.225, constellation: "Canis Minor" },
  { name: "Betelgeuse", magnitude: -5.7, temperature: 3200, type: "M", distance: 548, radius: 887, ra: 88.793, dec: 7.407, constellation: "Orion" },
  { name: "Achernar", magnitude: -2.4, temperature: 20500, type: "B", distance: 139, radius: 9, ra: null, dec: null, constellation: "Eridanus" },
  { name: "Hadar", magnitude: -5.3, temperature: 25500, type: "B", distance: 390, radius: 8, ra: 210.956, dec: -60.373, constellation: "Centaurus" },
  { name: "Altair", magnitude: 2.2, temperature: 8060, type: "A", distance: 16.7, radius: 1.63, ra: 297.696, dec: 8.868, constellation: "Aquila" },
  { name: "Aldebaran", magnitude: -0.8, temperature: 4130, type: "K", distance: 65, radius: 44, ra: 68.980, dec: 16.509, constellation: "Taurus" },
  { name: "Spica", magnitude: -3.4, temperature: 25500, type: "B", distance: 250, radius: 7, ra: 201.298, dec: -11.161, constellation: "Virgo" },
  { name: "Antares", magnitude: -5.2, temperature: 3340, type: "M", distance: 550, radius: 883, ra: 247.352, dec: -26.432, constellation: "Scorpius" },
  { name: "Fomalhaut", magnitude: 2.0, temperature: 9060, type: "A", distance: 25, radius: 1.8, ra: 344.413, dec: -29.622, constellation: "Piscis Austrinus" },
  { name: "Pollux", magnitude: 1.0, temperature: 4900, type: "K", distance: 33.7, radius: 8.8, ra: 116.329, dec: 28.026, constellation: "Gemini" },
  { name: "Deneb", magnitude: -7.2, temperature: 9340, type: "A", distance: 2615, radius: 203, ra: 310.358, dec: 45.280, constellation: "Cygnus" },
  { name: "Beta Crucis", magnitude: -4.7, temperature: 28000, type: "B", distance: 353, radius: 11, ra: 191.930, dec: -59.689, constellation: "Crux" },
  { name: "Regulus", magnitude: -0.8, temperature: 13260, type: "B", distance: 79, radius: 3.1, ra: 152.093, dec: 11.967, constellation: "Leo" },
  { name: "Acrux", magnitude: -4.0, temperature: 28000, type: "B", distance: 321, radius: 5, ra: 186.650, dec: -63.099, constellation: "Crux" },
  { name: "Adhara", magnitude: -5.2, temperature: 23000, type: "B", distance: 430, radius: 9, ra: 104.656, dec: -28.972, constellation: "Canis Major" },
  { name: "Shaula", magnitude: -3.4, temperature: 25500, type: "B", distance: 700, radius: 7, ra: 263.402, dec: -37.104, constellation: "Scorpius" },
  { name: "Bellatrix", magnitude: -4.3, temperature: 23000, type: "B", distance: 243, radius: 5.8, ra: 81.283, dec: 6.350, constellation: "Orion" },
  { name: "Castor", magnitude: 1.2, temperature: 9620, type: "A", distance: 51, radius: 2.4, ra: 113.649, dec: 31.888, constellation: "Gemini" },
  { name: "Gacrux", magnitude: -0.5, temperature: 3750, type: "M", distance: 88, radius: 5, ra: 187.791, dec: -57.113, constellation: "Crux" },
  { name: "Beta Centauri", magnitude: -5.1, temperature: 25500, type: "B", distance: 390, radius: 9, ra: 210.956, dec: -60.373, constellation: "Centaurus" },
  { name: "Alpha Centauri B", magnitude: 5.8, temperature: 4730, type: "K", distance: 4.37, radius: 0.86, ra: 219.896, dec: -60.838, constellation: "Centaurus" },
  { name: "Al Na'ir", magnitude: -1.1, temperature: 15550, type: "B", distance: 390, radius: 8, ra: 330.960, dec: -46.961, constellation: "Grus" },
  { name: "Miaplacidus", magnitude: -0.6, temperature: 9300, type: "A", distance: 111, radius: 6, ra: 138.300, dec: -69.717, constellation: "Carina" },
  { name: "Elnath", magnitude: -1.6, temperature: 12400, type: "B", distance: 131, radius: 4.8, ra: 81.573, dec: 28.607, constellation: "Taurus" },
  { name: "Alnilam", magnitude: -6.2, temperature: 26950, type: "B", distance: 2000, radius: 24, ra: 84.053, dec: -1.202, constellation: "Orion" },
  { name: "Mirfak", magnitude: -4.6, temperature: 7700, type: "F", distance: 590, radius: 6.7, ra: 51.081, dec: 49.861, constellation: "Perseus" },
  { name: "Alnitak", magnitude: -5.9, temperature: 33600, type: "O", distance: 736, radius: 20, ra: 85.190, dec: -1.943, constellation: "Orion" },
  { name: "Dubhe", magnitude: 0.2, temperature: 4900, type: "K", distance: 123, radius: 20, ra: 165.932, dec: 61.751, constellation: "Ursa Major" },
  { name: "Alioth", magnitude: 0.4, temperature: 9900, type: "A", distance: 81, radius: 4, ra: 193.507, dec: 55.960, constellation: "Ursa Major" },
  { name: "Peacock", magnitude: -2.3, temperature: 20500, type: "B", distance: 180, radius: 15, ra: 306.412, dec: -56.735, constellation: "Pavo" },
  { name: "Kaus Australis", magnitude: -0.3, temperature: 11000, type: "B", distance: 77, radius: 7, ra: 276.043, dec: -34.385, constellation: "Sagittarius" },
  { name: "Theta Scorpii", magnitude: -5.6, temperature: 7400, type: "F", distance: 490, radius: 4.5, ra: 264.330, dec: -42.998, constellation: "Scorpius" },
  { name: "Atria", magnitude: -0.1, temperature: 4590, type: "K", distance: 390, radius: 4, ra: 252.166, dec: -69.028, constellation: "Triangulum Australe" },
  { name: "Alkaid", magnitude: -1.7, temperature: 20500, type: "B", distance: 104, radius: 8, ra: 206.885, dec: 49.313, constellation: "Ursa Major" },
  { name: "Alpha Crucis B", magnitude: -3.3, temperature: 20500, type: "B", distance: 321, radius: 5, ra: 186.647, dec: -63.099, constellation: "Crux" },
  { name: "Avior", magnitude: -2.1, temperature: 4900, type: "K", distance: 63, radius: 4, ra: 125.628, dec: -59.509, constellation: "Carina" },
  { name: "Delta Canis Majoris", magnitude: -8.0, temperature: 6100, type: "F", distance: 800, radius: 203, ra: 107.098, dec: -26.393, constellation: "Canis Major" },
  { name: "Alhena", magnitude: 0.0, temperature: 9900, type: "A", distance: 109, radius: 2.8, ra: 99.428, dec: 16.399, constellation: "Gemini" },
  { name: "Menkalinan", magnitude: 0.6, temperature: 9340, type: "A", distance: 82, radius: 3.5, ra: 89.882, dec: 44.947, constellation: "Auriga" },
  { name: "Polaris", magnitude: -4.6, temperature: 6100, type: "F", distance: 446, radius: 44, ra: 37.955, dec: 89.264, constellation: "Ursa Minor" },
  { name: "Mirzam", magnitude: -4.8, temperature: 25500, type: "B", distance: 500, radius: 7, ra: 95.675, dec: -17.956, constellation: "Canis Major" },
  { name: "Delta Vulpeculae", magnitude: 0.6, temperature: 9900, type: "A", distance: 90, radius: 2, ra: 308.305, dec: 27.814, constellation: "Vulpecula" },
  { name: "Proxima Centauri", magnitude: 15.5, temperature: 2670, type: "M", distance: 4.24, radius: 0.14, ra: 217.429, dec: -62.679, constellation: "Centaurus" },
  { name: "Barnard's Star", magnitude: 13.2, temperature: 2800, type: "M", distance: 5.96, radius: 0.2, ra: 269.452, dec: 4.693, constellation: "Ophiuchus" },
  { name: "Wolf 359", magnitude: 16.7, temperature: 2670, type: "M", distance: 7.78, radius: 0.16, ra: 164.121, dec: 7.015, constellation: "Leo" },
  { name: "L 726-8", magnitude: 15.5, temperature: 2670, type: "M", distance: 8.7, radius: 0.15, ra: 24.756, dec: -17.951, constellation: "Cetus" },
  { name: "UV Ceti", magnitude: 16.0, temperature: 2670, type: "M", distance: 8.7, radius: 0.15, ra: 24.757, dec: -17.950, constellation: "Cetus" },
  { name: "Sirius B", magnitude: 11.2, temperature: 14800, type: "DA", distance: 8.6, radius: 0.008, ra: 101.289, dec: -16.717, constellation: "Canis Major" },
  { name: "Ross 154", magnitude: 13.1, temperature: 2800, type: "M", distance: 9.7, radius: 0.2, ra: 282.456, dec: -23.836, constellation: "Sagittarius" },
  { name: "Ross 248", magnitude: 14.8, temperature: 2670, type: "M", distance: 10.3, radius: 0.19, ra: 355.479, dec: 44.177, constellation: "Andromeda" },
  { name: "Epsilon Eridani", magnitude: 6.1, temperature: 4590, type: "K", distance: 10.5, radius: 0.74, ra: 53.233, dec: -9.458, constellation: "Eridanus" },
  { name: "Ross 128", magnitude: 13.5, temperature: 2800, type: "M", distance: 11, radius: 0.18, ra: 176.935, dec: 0.805, constellation: "Virgo" },
  { name: "Epsilon Indi", magnitude: 7.0, temperature: 4130, type: "K", distance: 10.5, radius: 0.77, ra: 330.840, dec: -56.786, constellation: "Indus" },
  { name: "61 Cygni A", magnitude: 7.6, temperature: 4130, type: "K", distance: 11.4, radius: 0.66, ra: 316.725, dec: 38.749, constellation: "Cygnus" },
  { name: "61 Cygni B", magnitude: 8.4, temperature: 3870, type: "K", distance: 11.4, radius: 0.6, ra: 316.730, dec: 38.742, constellation: "Cygnus" },
  { name: "Tau Ceti", magnitude: 5.7, temperature: 5150, type: "G", distance: 11.9, radius: 0.79, ra: 26.017, dec: -15.937, constellation: "Cetus" },
  { name: "Procyon B", magnitude: 13.0, temperature: 9700, type: "DF", distance: 11.4, radius: 0.009, ra: 114.825, dec: 5.224, constellation: "Canis Minor" },
  { name: "Lacaille 9352", magnitude: 9.6, temperature: 3340, type: "M", distance: 10.7, radius: 0.5, ra: 346.467, dec: -35.853, constellation: "Piscis Austrinus" },
  { name: "YZ Ceti", magnitude: 14.1, temperature: 2670, type: "M", distance: 12.1, radius: 0.13, ra: 18.128, dec: -16.999, constellation: "Cetus" },
  { name: "Lacaille 8760", magnitude: 8.7, temperature: 3340, type: "K", distance: 13, radius: 0.5, ra: 319.314, dec: -38.867, constellation: "Microscopium" },
  { name: "Kapteyn's Star", magnitude: 10.9, temperature: 3480, type: "M", distance: 12.8, radius: 0.29, ra: 77.919, dec: -45.018, constellation: "Pictor" },
  { name: "Kruger 60A", magnitude: 11.9, temperature: 2940, type: "M", distance: 13.1, radius: 0.23, ra: 330.794, dec: 57.702, constellation: "Cepheus" },
  { name: "Kruger 60B", magnitude: 13.3, temperature: 2670, type: "M", distance: 13.1, radius: 0.15, ra: 330.794, dec: 57.702, constellation: "Cepheus" },
  { name: "Ross 614A", magnitude: 13.1, temperature: 2800, type: "M", distance: 13.4, radius: 0.21, ra: 97.347, dec: -2.814, constellation: "Monoceros" },
  { name: "van Maanen's Star", magnitude: 14.2, temperature: 13000, type: "DB", distance: 14, radius: 0.011, ra: 2.529, dec: 5.233, constellation: "Pisces" },
  { name: "TZ Arietis", magnitude: 14.0, temperature: 2800, type: "M", distance: 14.5, radius: 0.2, ra: 30.054, dec: 13.052, constellation: "Aries" },
  { name: "AD Leonis", magnitude: 11.0, temperature: 2940, type: "M", distance: 16.2, radius: 0.44, ra: 154.901, dec: 19.870, constellation: "Leo" },
  { name: "40 Eridani A", magnitude: 6.0, temperature: 4900, type: "K", distance: 16.3, radius: 0.6, ra: 63.817, dec: -7.653, constellation: "Eridanus" },
  { name: "40 Eridani B", magnitude: 11.1, temperature: 10000, type: "DA", distance: 16.3, radius: 0.014, ra: 63.841, dec: -7.658, constellation: "Eridanus" },
  { name: "40 Eridani C", magnitude: 12.8, temperature: 2940, type: "M", distance: 16.3, radius: 0.16, ra: 63.840, dec: -7.656, constellation: "Eridanus" },
  { name: "70 Ophiuchi A", magnitude: 5.8, temperature: 4950, type: "K", distance: 16.7, radius: 0.85, ra: 271.364, dec: 2.500, constellation: "Ophiuchus" },
  { name: "70 Ophiuchi B", magnitude: 7.5, temperature: 3870, type: "K", distance: 16.7, radius: 0.61, ra: 271.364, dec: 2.499, constellation: "Ophiuchus" },
  { name: "EV Lacertae", magnitude: 11.7, temperature: 2800, type: "M", distance: 16.7, radius: 0.36, ra: 341.707, dec: 44.334, constellation: "Lacerta" },
];

const PLANETS = [
  {
    name: "Mercury", distance_million_km: 57.9, diameter_km: 4879, mass_earth_masses: 0.055,
    orbital_period_days: 88, rotation_period_hours: 1407.6, moons: 0, type: "Rocky Planet",
    mythology: "Named after the Roman messenger god Mercury (Greek: Hermes), known for his speed. The fastest planet seemed a fitting tribute to the swift-footed deity who delivered messages between gods and mortals.",
    fun_facts: "Smallest planet, closest to the Sun. Has the most eccentric orbit of all planets. One day on Mercury (sunrise to sunrise) lasts 176 Earth days! Surface temperature varies from -290°F to 800°F. Has a large iron core making it very dense. No atmosphere to speak of.",
    color: "#b5b5b5"
  },
  {
    name: "Venus", distance_million_km: 108.2, diameter_km: 12104, mass_earth_masses: 0.815,
    orbital_period_days: 225, rotation_period_hours: 5832.5, moons: 0, type: "Rocky Planet",
    mythology: "Named after the Roman goddess of love and beauty (Greek: Aphrodite). As the brightest natural object in the night sky after the Moon, ancient observers found it beautiful and worthy of the goddess's name.",
    fun_facts: "Hottest planet in our solar system at 900°F due to runaway greenhouse effect. Rotates backwards compared to most planets. A day on Venus (243 Earth days) is longer than its year (225 Earth days)! Thick clouds of sulfuric acid. Called Earth's 'sister planet' due to similar size.",
    color: "#e8cda0"
  },
  {
    name: "Mars", distance_million_km: 227.9, diameter_km: 6792, mass_earth_masses: 0.107,
    orbital_period_days: 687, rotation_period_hours: 24.6, moons: 2, type: "Rocky Planet",
    mythology: "Named after the Roman god of war (Greek: Ares) due to its blood-red color, which ancient cultures associated with bloodshed and battle. The planet's two moons, Phobos (Fear) and Deimos (Dread), are named after the god's companions.",
    fun_facts: "The Red Planet gets its color from iron oxide (rust). Home to Olympus Mons, the largest volcano in the solar system. Has polar ice caps of water and CO2. Day length is very similar to Earth (24.6 hours). Future target for human colonization.",
    color: "#c1440e"
  },
  {
    name: "Jupiter", distance_million_km: 778.5, diameter_km: 139820, mass_earth_masses: 317.8,
    orbital_period_days: 4333, rotation_period_hours: 9.9, moons: 95, type: "Gas Giant",
    mythology: "Named after the king of the Roman gods (Greek: Zeus), ruler of the sky and thunder. As the largest planet, it deserved the name of the most powerful deity.",
    fun_facts: "Largest planet - could fit all other planets inside it. The Great Red Spot is a storm larger than Earth that has raged for at least 400 years. Has 95 known moons including the four large Galilean moons. Acts as a 'cosmic vacuum cleaner' protecting inner planets from asteroids.",
    color: "#c88b3a"
  },
  {
    name: "Saturn", distance_million_km: 1430, diameter_km: 116460, mass_earth_masses: 95.2,
    orbital_period_days: 10759, rotation_period_hours: 10.7, moons: 146, type: "Gas Giant",
    mythology: "Named after the Roman god of agriculture and time (Greek: Cronus), father of Jupiter. In mythology, Saturn was dethroned by Jupiter.",
    fun_facts: "Famous for its spectacular ring system made of ice and rock particles. Rings are 175,000 miles wide but only 30 feet thick! Least dense planet - would float in water. Has 146 known moons, most in the solar system.",
    color: "#ead6a6"
  },
  {
    name: "Uranus", distance_million_km: 2871, diameter_km: 50724, mass_earth_masses: 14.5,
    orbital_period_days: 30687, rotation_period_hours: 17.2, moons: 27, type: "Ice Giant",
    mythology: "Named after the Greek god of the sky, Uranus (father of Saturn/Cronus). The only planet named after a Greek rather than Roman deity.",
    fun_facts: "Rotates on its side - axial tilt of 98°, possibly due to ancient collision. Appears blue-green due to methane. Has faint rings discovered in 1977. Winds can reach 560 mph.",
    color: "#73c7d4"
  },
  {
    name: "Neptune", distance_million_km: 4497, diameter_km: 49244, mass_earth_masses: 17.1,
    orbital_period_days: 60190, rotation_period_hours: 16.1, moons: 14, type: "Ice Giant",
    mythology: "Named after the Roman god of the sea (Greek: Poseidon), fitting for its deep blue color resembling ocean waters.",
    fun_facts: "Windiest planet with speeds up to 1,200 mph. Deep blue color from methane in atmosphere. Discovered through mathematical predictions rather than observation. Coldest planet atmosphere at -330°F.",
    color: "#3f54ba"
  },
  {
    name: "Pluto", distance_million_km: 5906, diameter_km: 2376, mass_earth_masses: 0.002,
    orbital_period_days: 90560, rotation_period_hours: 153.3, moons: 5, type: "Dwarf Planet",
    mythology: "Named after the Roman god of the underworld (Greek: Hades) in 1930 by 11-year-old Venetia Burney. Reclassified as a dwarf planet in 2006.",
    fun_facts: "Heart-shaped region called Tombaugh Regio discovered by New Horizons in 2015. Takes 248 years to orbit the Sun. Sometimes closer to Sun than Neptune.",
    color: "#c9b8a4"
  }
];

const MESSIER_OBJECTS = [
  { name: "Andromeda Galaxy", type: "Galaxy", constellation: "Andromeda", mag: 3.4, ra: 10.68, dec: 41.27, distance_ly: 2500000, description: "Our nearest galactic neighbor and the most distant object visible to the naked eye." },
  { name: "Orion Nebula", type: "Nebula", constellation: "Orion", mag: 4.0, ra: 83.82, dec: -5.39, distance_ly: 1344, description: "A bright stellar nursery visible to the naked eye as the middle 'star' in Orion's sword." },
  { name: "Pleiades", type: "Open Cluster", constellation: "Taurus", mag: 1.6, ra: 56.75, dec: 24.12, distance_ly: 444, description: "The Seven Sisters. A stunning blue reflection nebula and cluster." },
  { name: "Hercules Cluster", type: "Globular Cluster", constellation: "Hercules", mag: 5.8, ra: 250.42, dec: 36.46, distance_ly: 22000, description: "A massive ball of several hundred thousand stars." },
  { name: "Whirlpool Galaxy", type: "Galaxy", constellation: "Canes Venatici", mag: 8.4, ra: 202.47, dec: 47.19, distance_ly: 23000000, description: "A classic spiral galaxy interacting with a smaller companion galaxy." },
  { name: "Ring Nebula", type: "Planetary Nebula", constellation: "Lyra", mag: 8.8, ra: 283.40, dec: 33.03, distance_ly: 2000, description: "The glowing remains of a sun-like star that shed its outer layers." },
  { name: "Crab Nebula", type: "Supernova Remnant", constellation: "Taurus", mag: 8.4, ra: 83.63, dec: 22.01, distance_ly: 6500, description: "The remnant of a massive star explosion observed by Chinese astronomers in 1054 AD." },
  { name: "Lagoon Nebula", type: "Nebula", constellation: "Sagittarius", mag: 6.0, ra: 271.03, dec: -24.38, distance_ly: 4100, description: "A giant interstellar cloud in the constellation Sagittarius." },
  { name: "Sombrero Galaxy", type: "Galaxy", constellation: "Virgo", mag: 8.0, ra: 189.99, dec: -11.62, distance_ly: 29000000, description: "A spiral galaxy seen edge-on with a prominent dust lane resembling a hat." },
  { name: "Eagle Nebula", type: "Nebula", constellation: "Serpens", mag: 6.4, ra: 274.70, dec: -13.81, distance_ly: 7000, description: "Famous for the 'Pillars of Creation' photographed by Hubble." },
  { name: "Dumbbell Nebula", type: "Planetary Nebula", constellation: "Vulpecula", mag: 7.4, ra: 299.90, dec: 22.72, distance_ly: 1360, description: "The first planetary nebula to be discovered." },
  { name: "Triangulum Galaxy", type: "Galaxy", constellation: "Triangulum", mag: 5.7, ra: 23.46, dec: 30.66, distance_ly: 3000000, description: "The third-largest member of our Local Group of galaxies." },
  { name: "Beehive Cluster", type: "Open Cluster", constellation: "Cancer", mag: 3.7, ra: 130.10, dec: 19.68, distance_ly: 577, description: "One of the nearest open clusters to Earth." },
  { name: "Bode's Galaxy", type: "Galaxy", constellation: "Ursa Major", mag: 6.9, ra: 148.89, dec: 69.07, distance_ly: 12000000, description: "A grand design spiral galaxy near the Big Dipper." },
  { name: "Cigar Galaxy", type: "Galaxy", constellation: "Ursa Major", mag: 8.4, ra: 148.97, dec: 69.68, distance_ly: 12000000, description: "A starburst galaxy appearing edge-on near Bode's Galaxy." },
  { name: "Wild Duck Cluster", type: "Open Cluster", constellation: "Scutum", mag: 5.8, ra: 282.76, dec: -6.27, distance_ly: 6200, description: "One of the richest and most compact open clusters." },
  { name: "Butterfly Cluster", type: "Open Cluster", constellation: "Scorpius", mag: 4.2, ra: 263.40, dec: -32.22, distance_ly: 1600, description: "A bright cluster that resembles the shape of a butterfly." },
  { name: "Ptolemy's Cluster", type: "Open Cluster", constellation: "Scorpius", mag: 3.3, ra: 268.28, dec: -34.79, distance_ly: 980, description: "A large cluster visible to the naked eye near the stinger of the Scorpion." },
  { name: "Omega Centauri", type: "Globular Cluster", constellation: "Centaurus", mag: 3.9, ra: 201.70, dec: -47.48, distance_ly: 15800, description: "The largest globular cluster in the Milky Way, containing millions of stars." },
];

const CONSTELLATION_INFO = {
  "Orion": { description: "The Hunter", mythology: "Orion was a giant huntsman in Greek mythology. According to legend, he boasted that he could hunt any animal on Earth. The goddess Artemis (or Gaia in some versions) sent a scorpion to kill him. Both Orion and the scorpion were placed in the sky, but on opposite sides so they would never meet.", features: "Home to the famous Orion's Belt (three bright stars in a row), the Orion Nebula (a stellar nursery visible to the naked eye), and two brilliant stars: Betelgeuse (red supergiant) and Rigel (blue supergiant).", best_season: "Winter (December - February)" },
  "Canis Major": { description: "The Great Dog", mythology: "One of Orion's hunting dogs. In Greek mythology, Canis Major follows Orion across the sky. Some legends say this is Laelaps, the dog that never failed to catch what it was hunting, given as a gift to Europa by Zeus.", features: "Contains Sirius, the brightest star in the night sky, known as the 'Dog Star'. Ancient Egyptians used Sirius's rising to predict the flooding of the Nile River.", best_season: "Winter (January - March)" },
  "Ursa Major": { description: "The Great Bear", mythology: "Callisto, a nymph, was transformed into a bear by the jealous goddess Hera. Her son Arcas nearly killed her while hunting, but Zeus placed them both in the sky as Ursa Major and Ursa Minor.", features: "Contains the Big Dipper asterism, one of the most recognizable star patterns. The pointer stars (Dubhe and Merak) point toward Polaris, the North Star.", best_season: "Spring (March - May), visible year-round in northern latitudes" },
  "Centaurus": { description: "The Centaur", mythology: "Often identified with Chiron, the wise centaur who tutored many Greek heroes including Achilles, Hercules, and Jason. Unlike other centaurs, Chiron was known for his wisdom, kindness, and knowledge of medicine.", features: "Home to Alpha Centauri, our closest stellar neighbor (4.37 light-years away), and Proxima Centauri, the closest individual star.", best_season: "Spring (April - June), primarily visible from Southern Hemisphere" },
  "Lyra": { description: "The Lyre (Harp)", mythology: "The lyre of Orpheus, the legendary musician whose music could charm all living things and even stones. When Orpheus died, Zeus placed his lyre in the heavens.", features: "Dominated by Vega, one of the brightest stars in the sky and part of the Summer Triangle.", best_season: "Summer (July - September)" },
  "Crux": { description: "The Southern Cross", mythology: "Though not from ancient mythology, Crux holds deep significance for many cultures. Indigenous Australians saw it as various animals and objects. It's featured on several national flags.", features: "The smallest of all 88 constellations but one of the most distinctive. Used for navigation in the Southern Hemisphere.", best_season: "Autumn/Fall (April - June), visible only from Southern Hemisphere" },
  "Scorpius": { description: "The Scorpion", mythology: "The scorpion that killed Orion. Gaia sent a scorpion to humble Orion after he boasted he could kill any creature. They were placed on opposite sides of the sky.", features: "Contains Antares, a red supergiant whose name means 'rival of Mars'. The constellation actually looks like a scorpion.", best_season: "Summer (June - August)" },
  "Gemini": { description: "The Twins", mythology: "Represents Castor and Pollux, twin half-brothers. Pollux was immortal (son of Zeus) while Castor was mortal. When Castor died, Pollux shared his immortality.", features: "The two brightest stars, Castor and Pollux, mark the heads of the twins.", best_season: "Winter (January - March)" },
  "Aquila": { description: "The Eagle", mythology: "The eagle that carried Zeus's thunderbolts. In some myths, this is the eagle that abducted Ganymede to serve as cupbearer to the gods.", features: "Contains Altair, one of the closest naked-eye stars at 17 light-years. Part of the Summer Triangle.", best_season: "Summer (July - September)" },
  "Taurus": { description: "The Bull", mythology: "Represents the form Zeus took to abduct Europa. Zeus transformed into a beautiful white bull, and when Europa climbed on his back, he carried her across the sea to Crete.", features: "Contains the Pleiades (Seven Sisters) star cluster and the Hyades cluster. The Crab Nebula is also in Taurus.", best_season: "Winter (November - January)" },
  "Leo": { description: "The Lion", mythology: "Represents the Nemean Lion, killed by Hercules as his first labor. Hercules strangled it with his bare hands since weapons couldn't pierce its skin.", features: "Contains Regulus, a bright blue star marking the lion's heart.", best_season: "Spring (March - May)" },
  "Virgo": { description: "The Virgin/Maiden", mythology: "Associated with several goddesses: Demeter (goddess of harvest), her daughter Persephone, or Astraea (goddess of justice). Often depicted holding wheat, represented by Spica.", features: "Home to the Virgo Cluster, containing over 1,000 galaxies. Virgo is the largest zodiac constellation.", best_season: "Spring (April - June)" },
  "Cygnus": { description: "The Swan", mythology: "Zeus disguised as a swan to seduce Leda, or the story of Phaethon whose friend Cygnus dove repeatedly into a river to retrieve his body.", features: "Forms the Northern Cross asterism. Contains Deneb, one of the most luminous stars known.", best_season: "Summer (August - October)" },
  "Canis Minor": { description: "The Little Dog", mythology: "Orion's smaller hunting dog, often said to be Maera, the dog of Icarius.", features: "Contains Procyon, the eighth brightest star in the night sky. Procyon means 'before the dog'.", best_season: "Winter (February - March)" },
  "Boötes": { description: "The Herdsman/Bear Driver", mythology: "Often identified as Arcas driving the bears around the celestial pole. Others say he's the inventor of the plow.", features: "Contains Arcturus, the fourth brightest star in the night sky.", best_season: "Spring (May - July)" },
  "Auriga": { description: "The Charioteer", mythology: "Erichthonius, who invented the four-horse chariot. Often depicted carrying a goat and kids.", features: "Contains Capella, the sixth brightest star in the sky.", best_season: "Winter (December - February)" },
  "Eridanus": { description: "The River", mythology: "Represents the river into which Phaethon fell after losing control of Apollo's sun chariot.", features: "Contains Achernar, one of the flattest stars known due to rapid rotation.", best_season: "Winter (December - January)" },
  "Piscis Austrinus": { description: "The Southern Fish", mythology: "Often associated with the Syrian fertility goddess Atargatis.", features: "Contains Fomalhaut, which has a debris disk and at least one planet.", best_season: "Autumn/Fall (October - November)" },
  "Sagittarius": { description: "The Archer", mythology: "Usually depicted as a centaur archer, representing the satyr Crotus, son of Pan, who invented archery.", features: "Points toward the center of our Milky Way galaxy. The 'Teapot' asterism is easily recognizable.", best_season: "Summer (July - August)" },
  "Carina": { description: "The Keel (of a ship)", mythology: "Part of the larger constellation Argo Navis, the ship of Jason and the Argonauts.", features: "Contains Canopus, the second brightest star. Home to Eta Carinae, a massive unstable star.", best_season: "Summer (February - April), Southern Hemisphere" },
  "Perseus": { description: "The Hero", mythology: "Perseus, son of Zeus, famous for slaying Medusa the Gorgon. He used her severed head to rescue Andromeda.", features: "Contains Algol, the 'Demon Star', an eclipsing binary that changes brightness.", best_season: "Autumn/Fall (November - December)" },
  "Pavo": { description: "The Peacock", mythology: "The peacock was sacred to Hera. The eyes on its tail feathers came from the hundred-eyed giant Argus.", features: "Contains the bright star Peacock (Alpha Pavonis).", best_season: "Winter (July - September), Southern Hemisphere" },
  "Triangulum Australe": { description: "The Southern Triangle", mythology: "A modern constellation with no ancient mythology, created by navigators in the 16th century.", features: "Contains Atria, a bright orange giant.", best_season: "Winter (June - July), Southern Hemisphere" },
  "Grus": { description: "The Crane", mythology: "A modern constellation created in the late 16th century. The crane symbolizes vigilance and loyalty.", features: "Contains Alnair, a bright blue star. The constellation resembles a bird in flight.", best_season: "Autumn/Fall (September - October)" },
  "Vulpecula": { description: "The Little Fox", mythology: "Created in the 17th century by Johannes Hevelius, originally 'the little fox with the goose'.", features: "Home to the Dumbbell Nebula (M27), one of the brightest planetary nebulae.", best_season: "Summer (August - September)" },
  "Ophiuchus": { description: "The Serpent Bearer", mythology: "Represents Asclepius, the god of medicine and healing, son of Apollo. Zeus killed him for defying death.", features: "Often called the '13th zodiac sign'. Contains Barnard's Star, one of the closest to Earth.", best_season: "Summer (July - August)" },
  "Cetus": { description: "The Sea Monster/Whale", mythology: "The sea monster sent by Poseidon to devour Andromeda. Perseus rescued her with Medusa's head.", features: "Contains Mira, a famous variable star, and Tau Ceti, a close Sun-like star.", best_season: "Autumn/Fall (November - December)" },
  "Indus": { description: "The Indian", mythology: "A modern constellation created in the late 16th century.", features: "Contains Epsilon Indi, one of the closest stars to our solar system.", best_season: "Spring (September - October), Southern Hemisphere" },
  "Draco": { description: "The Dragon", mythology: "Ladon, the dragon who guarded the golden apples of the Hesperides, slain by Hercules.", features: "Long, winding constellation around the north celestial pole. Contains the Cat's Eye Nebula.", best_season: "Summer (July - August), circumpolar" },
  "Andromeda": { description: "The Chained Maiden", mythology: "Princess Andromeda was chained to a rock as a sacrifice to Cetus because her mother Cassiopeia boasted of her beauty.", features: "Home to the Andromeda Galaxy (M31), the nearest major galaxy at 2.5 million light-years.", best_season: "Autumn/Fall (October - November)" },
  "Monoceros": { description: "The Unicorn", mythology: "A modern constellation created in the 17th century.", features: "Contains the Rosette Nebula and Plaskett's star, one of the most massive binaries known.", best_season: "Winter (January - February)" },
  "Pisces": { description: "The Fishes", mythology: "Aphrodite and Eros transformed into fish to escape the monster Typhon. They tied themselves together.", features: "A zodiac constellation containing the vernal equinox point.", best_season: "Autumn/Fall (October - November)" },
  "Microscopium": { description: "The Microscope", mythology: "Created by Lacaille to honor scientific instruments.", features: "One of the faintest constellations with no bright stars.", best_season: "Spring (September), Southern Hemisphere" },
  "Pictor": { description: "The Painter's Easel", mythology: "Created by Lacaille in the 18th century.", features: "Contains Beta Pictoris, a young star with a prominent debris disk forming planets.", best_season: "Summer (January - February), Southern Hemisphere" },
  "Lacerta": { description: "The Lizard", mythology: "Created by Hevelius in the 17th century.", features: "A small, faint constellation crossed by the Milky Way.", best_season: "Autumn/Fall (October)" },
  "Aries": { description: "The Ram", mythology: "The golden ram whose fleece became the Golden Fleece sought by Jason and the Argonauts.", features: "A zodiac constellation. The vernal equinox was once located here.", best_season: "Autumn/Fall (November - December)" },
  "Sculptor": { description: "The Sculptor's Workshop", mythology: "Created by Lacaille to honor the art of sculpture.", features: "Contains the south galactic pole and the Sculptor Galaxy.", best_season: "Autumn/Fall (October - November)" },
  "Aquarius": { description: "The Water Bearer", mythology: "Often identified with Ganymede, abducted by Zeus to serve as cupbearer to the gods.", features: "Contains the Helix Nebula, one of the closest planetary nebulae to Earth.", best_season: "Autumn/Fall (September - October)" },
  "Ursa Minor": { description: "The Little Bear", mythology: "Represents Arcas, son of Callisto, turned into a bear by Zeus.", features: "Contains Polaris, the North Star. Forms the Little Dipper asterism.", best_season: "Visible year-round from northern latitudes (circumpolar)" },
  "Cepheus": { description: "The King", mythology: "King Cepheus of Ethiopia, husband of Cassiopeia and father of Andromeda.", features: "Contains Delta Cephei, the prototype Cepheid variable star used for cosmic distance measurement.", best_season: "Autumn/Fall (October - November), circumpolar" },
  "Solar System": { description: "Our Home", mythology: "The Sun is our home star!", features: "The Sun is a G-type main-sequence star that has been shining for about 4.6 billion years.", best_season: "Visible during daytime!" },
};

const CONSTELLATION_LINES = {
  "Orion": [["Betelgeuse","Bellatrix"],["Bellatrix","Alnitak"],["Alnitak","Alnilam"],["Rigel","Bellatrix"],["Betelgeuse","Alnilam"]],
  "Ursa Major": [["Dubhe","Alioth"],["Alioth","Alkaid"]],
  "Gemini": [["Castor","Pollux"],["Castor","Alhena"],["Pollux","Alhena"]],
  "Scorpius": [["Antares","Shaula"]],
  "Cygnus": [["Deneb","61 Cygni A"]],
  "Taurus": [["Aldebaran","Elnath"]],
  "Crux": [["Acrux","Beta Crucis"],["Gacrux","Alpha Crucis B"]],
  "Centaurus": [["Alpha Centauri A","Hadar"]],
  "Canis Major": [["Sirius A","Mirzam"],["Sirius A","Adhara"]],
};

const SPECTRAL_TYPE_INFO = {
  "O": { label: "O-type", description: "Very hot, blue, very bright", color: "#9bb0ff", tempRange: "> 30,000 K" },
  "B": { label: "B-type", description: "Hot, blue-white, luminous", color: "#aabfff", tempRange: "10,000 – 30,000 K" },
  "A": { label: "A-type", description: "White, bright, often young stars like Vega", color: "#cad7ff", tempRange: "7,500 – 10,000 K" },
  "F": { label: "F-type", description: "Yellow-white, slightly cooler than A-type", color: "#f8f7ff", tempRange: "6,000 – 7,500 K" },
  "G": { label: "G-type", description: "Yellow, like the Sun, medium temperature", color: "#fff4ea", tempRange: "5,200 – 6,000 K" },
  "K": { label: "K-type", description: "Orange, cooler, smaller stars", color: "#ffd2a1", tempRange: "3,700 – 5,200 K" },
  "M": { label: "M-type", description: "Red, cool, often red dwarfs", color: "#ffcc6f", tempRange: "2,400 – 3,700 K" },
};

// Simplified planetary orbital elements for approximate positions
// (Used instead of Skyfield/JPL ephemeris which isn't available in browser)
const PLANET_ORBITS = {
  "Mercury": { a: 0.387, e: 0.2056, i: 7.0, period: 87.97, lon0: 252.25, lonRate: 4.09 },
  "Venus":   { a: 0.723, e: 0.0068, i: 3.39, period: 224.7, lon0: 181.98, lonRate: 1.602 },
  "Mars":    { a: 1.524, e: 0.0934, i: 1.85, period: 686.98, lon0: 355.45, lonRate: 0.524 },
  "Jupiter": { a: 5.203, e: 0.0484, i: 1.30, period: 4332.59, lon0: 34.40, lonRate: 0.083 },
  "Saturn":  { a: 9.537, e: 0.0542, i: 2.49, period: 10759.22, lon0: 49.94, lonRate: 0.034 },
  "Uranus":  { a: 19.19, e: 0.0472, i: 0.77, period: 30688.5, lon0: 313.23, lonRate: 0.012 },
  "Neptune": { a: 30.07, e: 0.0086, i: 1.77, period: 60182, lon0: 304.88, lonRate: 0.006 },
  "Pluto":   { a: 39.48, e: 0.2488, i: 17.16, period: 90560, lon0: 238.93, lonRate: 0.004 },
};
